import '@/styles/globals.css';

import classNames from 'classnames';
import type { Metadata } from 'next';
import { Nunito_Sans } from 'next/font/google';

import { Providers } from '@/app/providers';
import Header from '@/components/molecules/header';

const inter = Nunito_Sans({
  subsets: ['latin'],
  variable: '--font-nunito-sans',
});

export const metadata: Metadata = {
  title: 'Countries API',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const classes = classNames(inter.className, 'bg-light-98 dark:bg-dark-17');
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={classes}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
